### ISSUE TITLE
I love this package!

### ISSUE THREAD

**Issue by gabn88** [ezhome/django-webpack-loader#108]
I'm using it extensively in the dev environment now and I'm super enthousiastic about it.
The existence of this package is one of the reasons I'm using webpack for my frontend now, which has a lot of advantages I found out ;)

But one thing, would it be possible to update the PyPy version? :)

Thanks!

**Comment by gabn88** [comment]
And another question: Would it be possible to include util functions within the Django settings? (for example for tinymce)

**Comment by gabn88** [comment]
Actually, I also wrote a webpack_manifest context processor that might come to handy to some other people as well:

```
def webpack_manifest(request):
    # not used in the API!
    # creates inline manifest based on file
   

    webpack_config = load_config('DEFAULT')
    manifest_path  = os.path.join(settings.FRONTEND_DIR, 'assets', webpack_config['BUNDLE_DIR_NAME'], 'chunk-manifest.json')
        
    try:
        with open(manifest_path) as f:
            manifest_content = f.read()
    except IOError:
        raise IOError(
            'Error reading {0}. Did you create a manifest?'.format(
                manifest_path))

    

    inline_webpack_manifest = mark_safe('<script> \
                            //<![CDATA[\
                            window.webpackManifest = '+manifest_content+'\
                            //]]>\
                        </script>')

    return {'inline_webpack_manifest':inline_webpack_manifest}

```

Cheers!

**Comment by owais** [comment]
@gabn88 I've released a new version with latest changes from master. Thanks!
