### ISSUE TITLE
Allow webpack_static template tag to reference remote files

### ISSUE THREAD

**Issue by saily** [ezhome/django-webpack-loader#110]
Hi, 

i was playing around with [django-storages](https://github.com/jschneier/django-storages) and [django-minio-storage](https://github.com/tomhoule/django-minio-storage) to upload static files to aws s3 or minio s3 storage.

After a while i noticed this works fine except for my static ressources included with webpack-loader template tags as `render_bundle` or `webpack_static`. I digged into the code and round the fallback on `STATIC_URL` in `templatetags/webpack_loader.py` which was [already refactored on current master, but still has the same issue](https://github.com/owais/django-webpack-loader/blob/master/webpack_loader/utils.py#L59)

    @register.simple_tag
    def webpack_static(asset_name, config='DEFAULT'):
        return "{0}{1}".format(
            get_loader(config).get_assets().get(
                'publicPath', getattr(settings, 'STATIC_URL')
            ),
            asset_name
        )

When `publicPath` is set in stats file it's not possible to load it from remote, see #107. It might be a solution in #102 and use default static template tags, but basically this package should work with storage backends as:

- `minio_storage.storage.MinioStaticStorage`
- `storages.backends.s3boto3.S3Boto3Storage`
- `django.contrib.staticfiles.storage.ManifestStaticFilesStorage`
- `whitenoise.storage.CompressedManifestStaticFilesStorage`

I'd love to start a discussion here and make this package work with different storage backends and also consider people using whitenoise.

**Comment by owais** [comment]
Check my comment here https://github.com/ezhome/django-webpack-loader/issues/107#issuecomment-302396672 and https://github.com/ezhome/django-webpack-loader/issues/107#issuecomment-302399294

**Comment by owais** [comment]
Closing and moving discussion to #107
