### ISSUE TITLE
Flask support, and framework-agnosticism

### ISSUE THREAD

**Issue by gregplaysguitar** [ezhome/django-webpack-loader#111]
It'd be great to be able to use this lib outside of django - for example in a Flask project. Most of the core code doesn't require django, and could easily be converted, with a compatibility wrapper in webpack_loader.contrib.django. Is this something that you'd consider?
 
I realise it'd involve a pretty serious refactor, and perhaps it'd be better as a new library. I'm happy to do the work either way, but I wanted to check if you had any thoughts first.

**Comment by owais** [comment]
I see the appeal of that but a lot if not most of the code in the package is very specific to Django. If we do take out the django agnostic parts into another lib, it'll end up being very small and simplistic to the point that it might be much simpler to implement that independently for flask.

However, if you believe it's worth it to make this change, I'm all for it but I cannot afford to spend time on it right now. Your contribution would be more than welcome but before you get to writing any code, I think it would be helpful if you could propose the idea here so we can discuss it first.

My main concern would be how we would organize the code and what the API for usage in Django (and flask) would look like.

**Comment by gregplaysguitar** [comment]
Cool, thanks for getting back to me - since raising this issue I've discovered https://github.com/nickjj/flask-webpack which is similar although seems less actively maintained. I think ideally I'd prefer to be able to use django-webpack-loader but flask-webpack is doing a reasonable job for now.
