### ISSUE TITLE
Tarball download has less commits than the master branch

### ISSUE THREAD

**Issue by slackmart** [ezhome/django-webpack-loader#114]
I've uncompressed the tarball file and then explored a little bit, looking for an answer for this question [Import not importing all functions?](http://stackoverflow.com/questions/43696215/import-not-importing-all-functions), and yes, I've found the answer: the `webpack_loader.utils` module doesn't have the latest changes.

I'm not sure about the reason but BTW here's the history for that file [utils.py](https://github.com/ezhome/django-webpack-loader/blame/master/webpack_loader/utils.py)

I've downloaded the tarball from https://github.com/owais/django-webpack-loader/tarball/0.4.0

Thanks in advance.

**Comment by gabn88** [comment]
Sorry to say, but nobody downloads tarballs these days... why don't you pip install git+https://github.com/ezhome/django-webpack-loader for the latest version?

**Comment by slackmart** [comment]
Maybe you're right. Inclusive that was the suggested way to go http://stackoverflow.com/questions/43696215/import-not-importing-all-functions/43737329#43737329

but I'm concerned why that changes are missing. The package is outdated but the more recent release was on Oct 26, 2016.

**Comment by owais** [comment]
I've just released 0.5.0 that contains code from latest master
