### ISSUE TITLE
Add a CHANGELOG file

### ISSUE THREAD

**Issue by saily** [ezhome/django-webpack-loader#115]
To make it easier for people upgrading to bleeding edge version of your great `django-webpack-loader` it makes sense to check `CHANGELOG` first, before upgrading.

**Comment by shapiromatron** [comment]
I can take a shot at an initial PR if you'd like; I can pull the content out of the tags and scrape the changes for v.0.4 and v.0.5 if you'd like; let me know if that's something you want @owais

**Comment by saily** [comment]
@shapiromatron there are some tools which can create `CHANGELOG` files out of commit history but starting with a simple `CHANGELOG.md` file - in which every new feature/bugfix/change must be mentioned - would already help people upgrading.

**Comment by owais** [comment]
Sound great @shapiromatron @saily. A PR would be great. Let's start with something simpler like @saily said.

**Comment by owais** [comment]
Thanks @shapiromatron
