### ISSUE TITLE
how to build a static bundle file for deployment if i was using webpack-dev-server?

### ISSUE THREAD

**Issue by untitledboy** [ezhome/django-webpack-loader#122]
i have been using webpack-dev-server for hot reload during development. but after my app is built i want to make a static bundle and i want to use it without running a development server. (without `$ node server.js`)

what is the best way of doing it?

**webpack.config.js**

	var path = require('path')
	var webpack = require('webpack')
	var BundleTracker = require('webpack-bundle-tracker')

	module.exports = {
		context: __dirname,
		entry: {
			'meet-simulator': [
				'webpack-dev-server/client?http://localhost:3000',
				'webpack/hot/only-dev-server',
				'./assets/js/index'
			]
		},
		output: {
			path: path.resolve('./assets/bundles/'),
			filename: '[name]-[hash].js',
			publicPath: 'http://localhost:3000/assets/bundles/',
		},
		plugins: [
			new webpack.HotModuleReplacementPlugin(),
			new webpack.NoEmitOnErrorsPlugin(),
			new BundleTracker({filename: './webpack-stats.json'}),

			new webpack.ProvidePlugin({
				$: 'jquery',
				jQuery: 'jquery',
				'window.jQuery': 'jquery'
			})
		],
		module: {
			loaders: [
				{
					test: /\.jsx?$/,
					exclude: /node_modules/,
					loaders: [
						'react-hot-loader',
						'babel-loader?presets[]=react',
					]
				}
			]
		},
		resolve: {
			modules: ['node_modules', 'bower_components'],
			extensions: ['.js', '.jsx']
		}
	}

**server.js**

	var webpack = require('webpack');
	var WebpackDevServer = require('webpack-dev-server');
	var config = require('./webpack.config');

	new WebpackDevServer(webpack(config), {
		publicPath: config.output.publicPath,
		hot: true,
		inline: true,
		historyApiFallback: true
	}).listen(3000, '0.0.0.0', function (err, result) {
		if (err){
			console.error(err);
		}

		console.log('Listening at 0.0.0.0:3000');
	});

**Comment by owais** [comment]
Don't use webpack devserver. Don't invoke server.js but directly use webpack CLI command. A simple example: https://github.com/ezhome/django-webpack-loader/tree/master/examples/simple and webpack docs https://webpack.js.org/

**Comment by littlehome-eugene** [comment]
Hello, I guess you wrote this article https://owais.lone.pw/blog/webpack-plus-reactjs-and-django/ @owais 

So it's advised against using webpack-dev-server now? 
we are using webpack4.
