### ISSUE TITLE
Using PickleSerializer causes error

### ISSUE THREAD

**Issue by mozartilize** [ezhome/django-webpack-loader#126]
Hi, I'm using PickleSerializer instead of JSONSerializer for session middleware and then errors occur for webpack loader template tags.

`Can't pickle <function render_bundle at 0x7f84bb528510>: it's not the same object as webpack_loader.templatetags.webpack_loader.render_bundle`

It happens usually, not always and to one template tag at a time.

Django version 1.11.2

**Comment by matthiask** [comment]
That's quite strange. Why would the `render_bundle` function even be a part of your session?

**Comment by mozartilize** [comment]
nvm, i did use this method anymore :)
