### ISSUE TITLE
Examples does not work.

### ISSUE THREAD

**Issue by huseyinyilmaz** [ezhome/django-webpack-loader#127]
First of all, thanks for implementing this project. It has become one of the standard packages I have been using.

(I installed dependencies through requirements.txt)
I ran the examples and got the following error:

```
(hotreloadtest) Huseyins-MacBook-Air-2:hot-reload huseyin$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
(hotreloadtest) Huseyins-MacBook-Air-2:hot-reload huseyin$
```

I am guessing that problem is wrong django version . I tried to find the correct django version by trying out each one, but I was not successful.

I think examples might need version pinned requirements and python version noted on README.

**Comment by matthiask** [comment]
It seems you haven't activated the virtualenv. This error can't have anything to do with django-webpack-loader, when not even Django is found.

**Comment by huseyinyilmaz** [comment]
Oups. You are absolutely right. This was a problem with my environment. Upon closer inspection I found the problem. Thanks for pointing that out.

**Comment by Bongsopha** [comment]
@huseyinyilmaz  Excuse me, can you tell me how to solve this problem?

**Comment by huseyinyilmaz** [comment]
@Bongsopha It seems like that was happening because I did not install the dependencies correctly.
