### ISSUE TITLE
Only loading scss and not normal css?

### ISSUE THREAD

**Issue by marcuslind90** [ezhome/django-webpack-loader#129]
In the `get_as_tags()` method things are filtered by .js or .scss files, **not by .css**. This makes me confused, webpack takes my scss and compiles them to css, so django-webpack-loader does not recognize my css files and does not load them into my template with the `{% render_bundle 'main' 'css' %}` template tag.

I feel like the `get_as_tags()` method should contain a third elif statement saying
```
elif chunk['name'].endswith(('.css', '.css.gz')):
    tags.append((
        '<link type="text/css" href="{0}" rel="stylesheet" {1}/>'
    ).format(chunk['url'], attrs))
```

I guess I somehow misunderstood how this module is suppose to be used. Information please?

**Comment by marcuslind90** [comment]
Just to clarify my issue I decided to include my `webpack.config.js` file to make it clearer what I'm trying to achieve.

As you can see, I'm trying to bundle both my ES2015 code and my SCSS code with the help of Webpack. Webpack is successfully bundling all my code and putting it in the `assets/dist` folder. Both a .js and a .css file is created.

When I in my template use `{% render_bundle 'main' 'css' %}`, nothing is loaded. When I go into python and I write `utils.get_as_tags()` it only returns the .js file. When I go into python and write `print(utils.get_files('main'))`, it prints out both files, including the .css file.

When I check the `get_as_tags` method, as I wrote in the first post, I can see that it only checks for `.js` and `.scss` files and generate the tags accordingly. This is where it gets confusing. If I add the `elif:`-statement from the first post, everything loads beautifully. But since it's not in the module by default, I suspect that I did some other issue. I'm sure other people that use this plugin has required to load CSS.

```
const path = require("path")
const ExtractTextPlugin = require("extract-text-webpack-plugin")
const BundleTracker = require("webpack-bundle-tracker")

const DIST_DIR = path.resolve(__dirname, "assets/dist")
const SRC_DIR = path.resolve(__dirname, "project")

const extractSass = new ExtractTextPlugin({
    filename: "[name].[contenthash].css",
    disable: process.env.NODE_ENV === "development",
    allChunks: true
})

module.exports = {
    context: __dirname,
    entry: SRC_DIR + '/static/project/js/index.js',
    output: {
        filename: '[name].[hash].js',
        path: DIST_DIR
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                include: [
                    SRC_DIR
                ],
                loader: "babel-loader",
                options: {
                    presets: ["es2015"]
                }
            },
            {
                test: /\.scss$/,
                use: extractSass.extract({
                    use: [
                        {
                            loader: "css-loader",
                            options: { sourceMap: true }
                        },
                        {
                            loader: "sass-loader",
                            options: { sourceMap: true }
                        }
                    ],
                    fallback: "style-loader"
                })
            },
            {
                test: /\.(otf|eot|svg|ttf|woff|woff2|png|jpg|jpeg)/,
                loader: "url-loader?limit=8192"
            }
        ]
    },
    plugins: [
        extractSass,
        new BundleTracker({
            filename: 'webpack-stats.json'
        })
    ]
}
```

**Comment by matthiask** [comment]
The code is `chunk['name'].endswith(('.css', '.css.gz'))`. Not sure what's going wrong, but looking for SCSS instead of CSS isn't it.

**Comment by owais** [comment]
This lib has no knowldge of scss whatsoever. Right now it strictly only loads js, js.gz, css and css.gz files.  I recommend to check the file names of your generated css bundles and confirm if they end in .css or .css.gz. 

Also, make sure you are using latest version of the app. We did not always have support for .gz
