### ISSUE TITLE
render_bundle not print proper paths

### ISSUE THREAD

**Issue by jeremytiki** [ezhome/django-webpack-loader#133]
I've been trying to integrate webpack-loader with my project. My project is setup as follows

Settings.py:
```
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'frontend/static/webpack-stats.json')
    }
}
```
.
├── ch
├── frontend
           ├── __init__.py
           ├── apps.py
           ├── src
           ├── static
           ├── templates
   ...
├── manage.py
├── static
└── utils

I'm keeping my webpack project in `./frontend` with webpack outputing to `./frontend/static/bundles`. `frontend` is a normal django app (hence the __init__.py and apps.py) so the static directory is automatically included in DEBUG.

Now when I try to use `render_bundle` to output my webpack project (app.js):

```
{% load render_bundle from webpack_loader %}
{% render_bundle 'app' %}
```
it renders to 
```
<script type="text/javascript" src="/bundles/js/app.js"></script>
<link type="text/css" href="/bundles/css/app.css" rel="stylesheet">
```
It should be
```
<script type="text/javascript" src="/static/bundles/js/app.js"></script>
<link type="text/css" href="/static/bundles/css/app.css" rel="stylesheet">
```

I didn't see anything in the docs about this issue, so sorry if I missed anything
EDIT:
I decided to see what `get_files` would do as well so I added this to the template:
```
{% load get_files from webpack_loader %}
{% get_files 'app' as app_files %}

{% for app_file in app_files %}
    <li>{{ app_file.name }} : {{ app_file.path }} : {{ app_file.publicPath }}</li>
{% endfor %}
```
and got the output
```
bundles/js/app.js : /home/jeremytiki/Projects/conference-helper/ch/frontend/static/bundles/js/app.js : /bundles/js/app.js
bundles/css/app.css : /home/jeremytiki/Projects/conference-helper/ch/frontend/static/bundles/css/app.css : /bundles/css/app.css
```
In this `app_file.path` is correct however other two (`app_file.name` and  `app_file.publicPath`) are missing the initial `/static`.

**Comment by dmitrykrylov** [comment]
@jeremytiki I have the same issue. Do you have any thoughts why it happens?

**Comment by lnorbi** [comment]
@jeremytiki Had the same issue, but managed to figure it out. Check your webpack configuration, specifically the `publicPath` property of `output`.
As far as I can see, the webpack-bundle-tracker output is used directly by this plugin to render the src tag, and webpack-bundle-tracker relies on the output setting of webpack itself.

If you check your `webpack-stats.json` file, you'll see a `publicPath` key for each chunk. This is what gets rendered by the plugin.
```
{
        "name": "bundles/app-7d3c1711b46ec35dd12a.js",
        "publicPath": "/static/bundles/app-7d3c1711b46ec35dd12a.js",
        "path": "D:\\DjangoDev\\Projects\\test1\\test1\\assets\\dist\\bundles\\app-7d3c1711b46ec35dd12a.js"
}
```

You need to make sure this is correct and matches your current Django settings.
Ensure that in your `webpack.config.js` you set it up as needed, e.g. if your `STATIC_URL='/static/'` :

```
output: {
	...
	publicPath: "/static/"
}
```

Hope this helps!

**Comment by owais** [comment]
@lnorbi is correct. Webpack's `publicPath` takes precedence over django's static path settings. If you want to use django's static URL settings, then don't set `publicPath` in webpack, otherwise set `publicPath` to a value that evaluates to correct filesystem paths.
