### ISSUE TITLE
Support static assets served by S3 in production 

### ISSUE THREAD

**Issue by heykarimoff** [ezhome/django-webpack-loader#142]
```{% render_bundle 'vendor' 'css' %}```
 ``` {% render_bundle 'storefront' 'css' %}```
Template tags rendering links to assets in locale filesystem, S3 storage is not supported.

**Comment by heykarimoff** [comment]
It is supported, just forget to configure `settings.py`

**Comment by jxltom** [comment]
@heykarimoff Hi, could you pleae tell me how to set ```settings.py```?

**Comment by heykarimoff** [comment]
@jxltom You need to set STATICFILES_STORAGE and AWS credentials
`    
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
`
