### ISSUE TITLE
Several single page apps?

### ISSUE THREAD

**Issue by typeshige** [ezhome/django-webpack-loader#150]
I successfully used this to make a React single page app served by Django.  Now I want to make another, is there documentation on how to do this?

**Comment by mlazowik** [comment]
If I understand correctly what you want, you need [multiple entry points](https://webpack.js.org/concepts/entry-points/#multi-page-application) in webpack. `django-webpack-loader` works just fine with that for us.

**Comment by jpic** [comment]
That works for us too so it looks fine to close the issue until its reopened.

**Comment by typeshige** [comment]
Perfect!! Thanks everyone! Closing...
